<a href="https://colab.research.google.com/github/Tony-Seo/HY_LM/blob/main/LM_TEST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(12+37)
print('python' + ' is exciting')

49
python is exciting


In [ ]:
import random

a=random.randint(10,20)
b=random.randint(10,20)

c=a+b
print(a,b,c)

12 19 31


In [ ]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)

[1 2 3 4]
(4,)
1
int64
8
4


In [ ]:
import numpy as np
a = np.array([i for i in range(10)])
b = np.array([i for i in range(10) if i % 2 == 0])
print(a)
print(b)
print(a.max())
print(a.min())
print(a.mean())

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
9
0
4.5


In [ ]:
import numpy as np

a = np.array([[1,1],[2,2],[3,3]])
print(a)
print(a.flatten())

[[1 1]
 [2 2]
 [3 3]]
[1 1 2 2 3 3]


In [ ]:
import numpy as np

a = np.array(np.random.randint(0, 99, size = 10))
print(a)
print(a.max())
print(a.min())
print(a.mean())

[56  6 92 40 34 40 55 72 39 38]
92
6
47.2


In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b;
print(a, b, c)

aa =np.array([1,2])
bb = np.array([3,4,5])
#cc = aa+bb;
#print(aa, bb, cc)

[1 2 3] [4 5 6] [5 7 9]


ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [ ]:
import numpy as np

a = np.array([[1,2],[3,4]])
print(a+1)
print(a-1)
print(a*100)
print(a/100)
print(a**2)
print(a%2)

[[2 3]
 [4 5]]
[[0 1]
 [2 3]]
[[100 200]
 [300 400]]
[[0.01 0.02]
 [0.03 0.04]]
[[ 1  4]
 [ 9 16]]
[[1 0]
 [1 0]]


In [ ]:
import numpy as np

print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.full((2,3),7))
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

#print(np.random.random((2,3)))

#print(np.arange(0,10))
#print(np.arange(0,10,2))

#print(np.linspace(0,10,3))

a = np.arange(0,10).reshape(2,5)
print(a)

print(np.transpose(a))
print(a.reshape(5,2))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
