<a href="https://colab.research.google.com/github/Tony-Seo/HY_LM/blob/main/LM_TEST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(12+37)
print('python' + ' is exciting')

49
python is exciting


In [ ]:
import random

a=random.randint(10,20)
b=random.randint(10,20)

c=a+b
print(a,b,c)

12 19 31


In [ ]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)

[1 2 3 4]
(4,)
1
int64
8
4


In [ ]:
import numpy as np
a = np.array([i for i in range(10)])
b = np.array([i for i in range(10) if i % 2 == 0])
print(a)
print(b)
print(a.max())
print(a.min())
print(a.mean())

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
9
0
4.5


In [ ]:
import numpy as np

a = np.array([[1,1],[2,2],[3,3]])
print(a)
print(a.flatten())

[[1 1]
 [2 2]
 [3 3]]
[1 1 2 2 3 3]


In [ ]:
import numpy as np

a = np.array(np.random.randint(0, 99, size = 10))
print(a)
print(a.max())
print(a.min())
print(a.mean())

[56  6 92 40 34 40 55 72 39 38]
92
6
47.2


In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b;
print(a, b, c)

aa =np.array([1,2])
bb = np.array([3,4,5])
#cc = aa+bb;
#print(aa, bb, cc)

[1 2 3] [4 5 6] [5 7 9]


ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [ ]:
import numpy as np

a = np.array([[1,2],[3,4]])
print(a+1)
print(a-1)
print(a*100)
print(a/100)
print(a**2)
print(a%2)

[[2 3]
 [4 5]]
[[0 1]
 [2 3]]
[[100 200]
 [300 400]]
[[0.01 0.02]
 [0.03 0.04]]
[[ 1  4]
 [ 9 16]]
[[1 0]
 [1 0]]


In [ ]:
import numpy as np

print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.full((2,3),7))
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

#print(np.random.random((2,3)))

#print(np.arange(0,10))
#print(np.arange(0,10,2))

#print(np.linspace(0,10,3))

a = np.arange(0,10).reshape(2,5)
print(a)

print(np.transpose(a))
print(a.reshape(5,2))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

bream_length = [
    25.4, 26.3, 26.5, 29.0, 29.0, 29.7, 29.7, 30.0, 30.0, 30.7,
    31.0, 31.0, 31.5, 32.0, 32.0, 32.0, 33.0, 33.0, 33.5, 33.5,
    34.0, 34.0, 34.5, 35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 38.5,
    38.5, 39.5, 41.0, 41.0, 42.0
]
bream_weight = [
     242,  290,  340,  363,  430,  450,  500,  390,  450,  500,
     475,  500,  500,  340,  600,  600,  700,  700,  610,  650,
     575,  685,  620,  680,  700,  725,  720,  714,  850, 1000,
     920,  955,  925,  975,  950
]

smelt_length = [
     9.8, 10.5, 10.6, 11.0, 11.2, 11.3, 11.8,
    11.8, 12.0, 12.2, 12.4, 13.0, 14.3, 15.0
]
smelt_weight = [
     6.7,  7.5,  7.0,  9.7,  9.8,  8.7, 10.0,
     9.9,  9.8, 12.2, 13.4, 12.2, 19.7, 19.9
]

length = bream_length + smelt_length
weight = bream_weight + smelt_weight

fish_data = [[l, w] for l, w in zip(length, weight)]
fish_target = [1] * len(bream_length) + [0] * len(smelt_length)

kn = KNeighborsClassifier(n_neighbors=5)
kn.fit(fish_data, fish_target)
print(kn.score(fish_data, fish_target))

1.0


In [1]:
import numpy as np

np.array([1, 'two', 3, 4])

array(['1', 'two', '3', '4'], dtype='<U21')

In [2]:
np.array([1, 'two', 3, 4], dtype = np.int32)

ValueError: invalid literal for int() with base 10: 'two'